apiVersion: apps/v1
kind: Deployment
metadata:
  name: egui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: egui
          image: billkeller/egui
          ports:
            - containerPort: 3000